=begin

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=end

fib = [1,2]
n = 0
increment_by = 1
sum_total = 0
done = false

def is_even(number)
    (number % 2 === 0) ? true : false
end


until done == true do
      if fib[n] >= 4000000 then
            done=true
            break
        else
            increment_by = fib[n] + fib[n+1]
            fib.push(increment_by)
   
            puts fib[n] 
            n = n+1
            
        end  
          
    
end
 puts "-------"  
puts fib
#reset counter variable
    
n = 0
    
puts "========"
        
while fib[n] < 4000000 do
        
            if is_even(fib[n]) then
            sum_total += fib[n]
            end
            n= n+1
       
end
    
puts sum_total
    



    